on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

name: "Build & Release"

jobs:
  android-build:
    name: Build & Release Android (Windows)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Build Android APK
        run: flutter build apk --release --split-per-abi

      - name: List APK directory contents for Android
        run: |
          echo "Contents of build/app/outputs/apk/release:"
          ls -R build/app/outputs/apk/release/

      - name: Push Android APK to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: |
            build/app/outputs/apk/release/*.apk  # Match any APK
          tag: v1.0.${{ github.run_number }}  # Use run number for uniqueness
          token: ${{ secrets.TOKEN }}
          skipIfReleaseExists: true  # Skip if the release already exists

  ios-build:
    name: Build & Release iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Build iOS IPA
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      - name: List IPA directory contents for iOS
        run: |
          echo "Contents of build/ios/iphoneos:"
          ls -R build/ios/iphoneos/

      - name: Push iOS IPA to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: build/ios/iphoneos/app.ipa  # Match the IPA
          tag: v1.0.${{ github.run_number }}  # Use run number for uniqueness
          token: ${{ secrets.TOKEN }}
          skipIfReleaseExists: true  # Skip if the release already exists

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [android-build, ios-build]  # Ensure this job runs after the Android and iOS jobs
    steps:
      - uses: actions/checkout@v3

      - name: Debug APK directory before release
        run: |
          echo "Checking APK directory:"
          ls -R build/app/outputs/apk/release/

      - name: Debug IPA directory before release
        run: |
          echo "Checking IPA directory:"
          ls -R build/ios/iphoneos/

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}  # Corrected to tag_name
          files: |
            build/app/outputs/apk/release/*.apk  # Match any APK
            build/ios/iphoneos/app.ipa  # Match IPA
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token to authenticate with GitHub
