name: "Build & Release"

on:
  pull_request:
    branches:
      - main
      - master
  push:
    branches:
      - main
      - master
      - develop

jobs:
  android-build:
    name: Build Android APK
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Build Android APK
        run: flutter build apk --release --split-per-abi

      - name: List APK Directory Contents
        run: |
          echo "Contents of build/app/outputs/flutter-apk/:"
          ls -R build/app/outputs/flutter-apk/

      - name: Upload APKs as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: android-apks
          path: build/app/outputs/flutter-apk/*.apk

  ios-build:
    name: Build iOS IPA
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Set Up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          architecture: x64

      - name: Build iOS IPA
        run: |
          flutter build ios --no-codesign
          cd build/ios/iphoneos
          mkdir Payload
          cd Payload
          ln -s ../Runner.app
          cd ..
          zip -r app.ipa Payload

      - name: List IPA Directory Contents
        run: |
          echo "Contents of build/ios/iphoneos/:"
          ls -R build/ios/iphoneos/

      - name: Upload IPA as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ios-ipa
          path: build/ios/iphoneos/app.ipa

  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [android-build, ios-build]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Download Android APKs
        uses: actions/download-artifact@v3
        with:
          name: android-apks
          path: ./android-apks

      - name: Download iOS IPA
        uses: actions/download-artifact@v3
        with:
          name: ios-ipa
          path: ./ios-ipa

      - name: List Downloaded Artifacts
        run: |
          echo "Android APKs:"
          ls -R ./android-apks
          echo "iOS IPA:"
          ls -R ./ios-ipa

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: Release v1.0.${{ github.run_number }}
          body: |
            Release of version v1.0.${{ github.run_number }}
          files: |
            ./android-apks/*.apk
            ./ios-ipa/*.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
